export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const SET_ENTITY = 'SET_ENTITY';
export const ADD_ENTITY = 'ADD_ENTITY';
export const UPDATE_ENTITY = 'UPDATE_ENTITY';
export const DELETE_ENTITY = 'DELETE_ENTITY';

export const ADD_INGREDIENT = 'ADD_INGREDIENT'; 
export const CHANGE_SOUCE = 'CHANGE_SOUCE';
export const CHANGE_DOUTH = 'CHANGE_DOUTH';
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const SET_PIZZA_NAME = 'SET_PIZZA_NAME';
export const RESET_PIZZA = 'RESET_PIZZA';

export const ADD_CURRENT_PIZZA = 'ADD_CURRENT_PIZZA';
export const CHANGE_PIZZA_COUNT = 'CHANGE_PIZZA_COUNT';
export const UPDATE_PIZZA = 'UPDATE_PIZZA';
export const UPDATE_PIZZA_PRICE = 'UPDATE_PIZZA_PRICE';
export const RESSET_PIZZA = 'RESSET_PIZZA';
export const ADD_MISK = 'ADD_MISK';
export const SET_DELIVERY_DATA = 'SET_DELIVERY_DATA';
export const CART_RESSET = 'CART_RESSET';

